FROM python:3.10

WORKDIR /app

COPY pyproject.toml uv.lock* ./

RUN pip install uv && \
    uv pip compile --generate-hashes pyproject.toml > requirements.txt && \
    uv pip install --system -r requirements.txt && \
    rm requirements.txt

COPY . .

EXPOSE 8001

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8001", "--reload"]

